FROM eclipse-temurin:25-jre

RUN mkdir -p /ds/tdb2 /ds/lucene

RUN apt update && apt install -y wget
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-5.6.0.tar.gz
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-5.6.0.tar.gz.sha512
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-5.6.0.tar.gz
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-5.6.0.tar.gz.sha512

RUN sha512sum -c apache-jena-fuseki-5.6.0.tar.gz.sha512
RUN sha512sum -c apache-jena-5.6.0.tar.gz.sha512

RUN tar -xzf apache-jena-5.6.0.tar.gz && rm apache-jena-5.6.0.tar.gz
RUN tar -xzf apache-jena-fuseki-5.6.0.tar.gz && rm apache-jena-fuseki-5.6.0.tar.gz
RUN mv apache-jena-fuseki-5.6.0 /usr/local/fuseki
RUN mv apache-jena-5.6.0 /usr/local/jena
RUN rm apache-jena-fuseki-5.6.0.tar.gz.sha512 apache-jena-5.6.0.tar.gz.sha512

ENV PATH="/usr/local/fuseki/bin:/usr/local/jena/bin:${PATH}"

COPY shiro.ini /usr/local/fuseki/run/shiro.ini
COPY config.ttl /usr/local/fuseki/run/config.ttl
WORKDIR /usr/local/fuseki

EXPOSE 3030

CMD ["./fuseki-server", "--config=/usr/local/fuseki/run/config.ttl"]