FROM tomcat:9

RUN mv /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps
COPY jena-fuseki-war-5.5.0.war /usr/local/tomcat/webapps/fuseki.war
COPY manager-context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

EXPOSE 8080

CMD ["catalina.sh", "run"]