FROM eclipse-temurin:21-jre

RUN mkdir /ds

RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-5.6.0.tar.gz
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-5.6.0.tar.gz.md5
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-5.6.0.tar.gz
RUN wget https://archive.apache.org/dist/jena/binaries/apache-jena-5.6.0.tar.gz.md5

RUN md5sum -c apache-jena-fuseki-5.6.0.tar.gz.md5
RUN md5sum -c apache-jena-5.6.0.tar.gz.md5

RUN tar -xzf apache-jena-5.6.0.tar.gz && rm apache-jena-5.6.0.tar.gz
RUN tar -xzf apache-jena-fuseki-5.6.0.tar.gz && rm apache-jena-fuseki-5.6.0.tar.gz
RUN mv apache-jena-fuseki-5.6.0 /usr/local/fuseki
RUN mv apache-jena-5.6.0 /usr/local/jena

ENV PATH="/usr/local/fuseki/bin:/usr/local/jena/bin:${PATH}"

COPY shiro.ini /usr/local/fuseki/run/shiro.ini
WORKDIR /usr/local/fuseki

EXPOSE 3030

CMD ["./fuseki-server", "--loc", "/ds", "--update", "/ds"]